# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

language: go
go:
  - 1.12.x

env:
  - GO111MODULE=on

before_install:
  # golangci-lint
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

before_script:
  # Get project dependencies
  - go mod download

script:
  - golangci-lint run
  - go test -v -race ./...
